# fly.toml app configuration file generated for about-me-website on 2024-11-03T19:34:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'about-me-website'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
